# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	NuGet.BuildTasks
DISTVERSION=	14.0.0.0-20162411
CATEGORIES=	devel

MAINTAINER=	dbn@dragon.local
COMMENT=	

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_GITHUB=	yes
GH_ACCOUNT=	NuGet
GH_TAGNAME=	4a57a0e

.include <bsd.port.mk>
