# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	cli
DISTVERSION=	1.0.0-rc2-20161124
CATEGORIES=	devel
DISTVERSIONPREFIX=	v

MAINTAINER=	mono@FreeBSD.org
COMMENT=	The .NET Core command-line tools

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	dotnet
GH_TAGNAME=	eb8e0cf

.include <bsd.port.mk>
