# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	nuget
PORTVERSION=	3.5.0
CATEGORIES=	devel

MAINTAINER=	dbn@dragon.local
COMMENT=	

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_GITHUB=	yes
GH_ACCOUNT=	NuGet
GH_PROJECT=	${GH_ACCOUNT}.Client
GH_TAGNAME=	59c90cb

.include <bsd.port.mk>
