# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

DOTNET_VERSION=	1.0.3
SDK_VERSION=	1.0.0-preview5-004226

.if ${PORTNAME} != dotnet-sdk
DOTNET_PORTVERSION=	1.1.0

BUILD_DEPENDS=	clang${LLVM_VERSION:S/.//}:lang/clang${LLVM_VERSION:S/.//} \
		bash:shells/bash

DISTVERSIONPREFIX=	v
USE_GITHUB=	yes
GH_ACCOUNT=	dotnet

USES+=		cmake shebangfix

CC=		clang${LLVM_VERSION:S/.//}
CXX=		clang++${LLVM_VERSION:S/.//}

BUILD_WRKSRC=	${BUILDDIR}
CMAKE_ARGS+=	-DCMAKE_INSTALL_PREFIX=${PREFIX}/${DOTNETDIR_SHARE}
CONFIGURE_ENV+=	BUILDDIR=${BUILDDIR}
INSTALL_TARGET=	install/strip
INSTALL_WRKSRC=	${BUILDDIR}
.endif

PLIST_SUB=	DOTNETDIR=${DOTNETDIR} \
		DOTNETDIR_SHARE=${DOTNETDIR_SHARE} \
		DOTNETDIR_SDK=${DOTNETDIR_SDK} \
		DOTNETDIR_FXR=${DOTNETDIR_FXR}

LLVM_VERSION=	3.8
LLVM_VER=	${LLVM_VERSION:S/.//}

BUILD_TOOLS_PACKAGE_VERSION=	`${CAT} ${WRKSRC}/BuildToolsVersion.txt`
BUILDDIR=	${WRKDIR}/.build
DOTNETDIR=	dotnet/bootstrap
DOTNETDIR_SHARE=${DOTNETDIR}/shared/Microsoft.NETCore.App/${DOTNET_VERSION}
DOTNETDIR_SDK=	${DOTNETDIR}/sdk/${SDK_VERSION}
DOTNETDIR_FXR=	${DOTNETDIR}/host/fxr/1.0.1

post-install:
	${FIND} ${STAGEDIR}${PREFIX}/${DOTNETDIR_SHARE} -name '*.dbg' -delete
