# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

DOTNETVERSION=	1.1.0
DISTVERSIONPREFIX=	v

BUILD_DEPENDS=	clang${LLVM_VERSION:S/.//}:lang/clang${LLVM_VERSION:S/.//} \
		bash:shells/bash

USE_GITHUB=	yes
GH_ACCOUNT=	dotnet

USES+=		cmake shebangfix

CC=		clang${LLVM_VERSION:S/.//}
CXX=		clang++${LLVM_VERSION:S/.//}

BUILD_WRKSRC=	${BUILDDIR}
CMAKE_ARGS+=	-DCMAKE_INSTALL_PREFIX=${PREFIX}/${DOTNETDIR_SHARE}
CONFIGURE_ENV+=	BUILDDIR=${BUILDDIR}
INSTALL_TARGET=	install/strip
INSTALL_WRKSRC=	${BUILDDIR}
PLIST_SUB=	DOTNETDIR=${DOTNETDIR} \
		DOTNETDIR_SHARE=${DOTNETDIR_SHARE} \
		DOTNETDIR_SDK=${DOTNETDIR_SDK} \
		DOTNETDIR_FXR=${DOTNETDIR_FXR}

BUILD_TOOLS_PACKAGE_VERSION=	`${CAT} ${WRKSRC}/BuildToolsVersion.txt`
BUILDDIR=	${WRKDIR}/.build
DOTNETDIR=	dotnet/bootstrap
DOTNETDIR_SHARE=${DOTNETDIR}/shared/Microsoft.NETCore.App/1.0.1
DOTNETDIR_SDK=	${DOTNETDIR}/sdk/${SDK_VERSION}
DOTNETDIR_FXR=	${DOTNETDIR}/host/fxr/1.0.1
LLVM_VERSION=	3.7
SDK_VERSION=	1.0.0-preview3-003686

post-install:
	${FIND} ${STAGEDIR}${PREFIX}/${DOTNETDIR_SHARE} -name '*.dbg' -delete
