# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	roslyn
PORTVERSION=	1.3.2
CATEGORIES=	lang

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/License.txt

USE_GITHUB=	yes
GH_ACCOUNT=	dotnet
GH_TAGNAME=	version-${PORTVERSION}

.include <bsd.port.mk>
